title: Nets eID Broker Privilege Management documentation
theme: just-the-docs

url: https://just-the-docs.github.io
logo: "/assets/nets-eid-broker.svg"
favicon_ico: "/assets/favicon.ico"
aux_links:
  GitHub Repository: https://github.com/Signaturgruppen-A-S/privilege-management-docs
