title: Signaturgruppen Privilege Management documentation
theme: just-the-docs

url: https://just-the-docs.github.io
logo: "/assets/broker-logo.png"
favicon_ico: "/assets/favicon.ico"
aux_links:
  GitHub Repository: https://github.com/Signaturgruppen-A-S/privilege-management-docs
